from updates.birth import birth
from updates.death import death
from updates.migration import migration
from updates.regional import regional
from updates.update_death import update_death
from updates.update_birth import update_birth
from updates.birth_infl import birth_infl
from updates.migration_infl import migration_infl
from updates.birth_and_death import birth_and_death
from updates.update_birth_fine import update_birth_fine
from updates.update_death_fine import update_death_fine
